  ********   DÉTERMINATION DU NOMBRE MAXIMUM DE MODALITÉS   *********;

%MACRO NMOD (MAR,MAXMOD)/store;
 PROC MEANS NOPRINT DATA=&&&MAR
      %IF %UPCASE(&NONREP)=OUI %THEN %DO;(WHERE=(R NE 1)) %END; ;
   VAR N;
   OUTPUT OUT=__NMAX MAX=;
 DATA _NULL_;
   SET __NMAX;
   N=INT(N)*(1-(N<0));
   CALL SYMPUT("&MAXMOD",LEFT(PUT(N,4.)));
 RUN;
 %IF &&&MAXMOD=0 %THEN %LET &MAXMOD=1;
 PROC DATASETS DDNAME=WORK NOLIST;
      DELETE __NMAX;
 QUIT;
%MEND NMOD;
