%MACRO VERIF3(MAR,U) / store;

%LOCAL NIV NCOMP NUMCAR;

%LET NIV=%SUBSTR(&MAR,4);
  DATA __DATAM;
    length var $32;
    SET &&&MAR;
    KEEP VAR N;
    VAR=LEFT(UPCASE(VAR));

  PROC SORT DATA=__DATAM OUT=__DATAMA;
    BY VAR;

  DATA __COMP __NUMCAR;
    MERGE _NOMVAR&U(IN=IN1) __DATAMA(IN=IN2);
    BY VAR;
    IF IN2 AND NOT IN1 THEN OUTPUT __COMP;
    IF IN1 AND IN2 AND N=0 AND TYPE=2 THEN OUTPUT __NUMCAR;
  RUN;

  %NOBSS(__COMP,NCOMP)

  %IF &NCOMP>0 %THEN
  %DO;
    %LET ER=1;
    PROC PRINT DATA=__COMP(KEEP=VAR);
      ID VAR;
      TITLE4 "ERREUR : LES VARIABLES SUIVANTES, DONT LES NOMS FIGURENT DANS LA"
             " VARIABLE VAR";
      TITLE5 "DE LA TABLE %UPCASE(&&&MAR)";
      TITLE6 "SPÉCIFIÉE DANS LE PARAMÈTRE &MAR, N'EXISTENT PAS";
      TITLE7 "DANS LA TABLE %UPCASE(&&&DATA&NIV)";
      TITLE8 "SPÉCIFIÉE DANS LE PARAMÈTRE DATA&NIV";
    RUN;
  %END;

  %ELSE %DO;
    %NOBSS(__NUMCAR,NUMCAR)
    %IF &NUMCAR>0 %THEN
    %DO;
      %LET ER=1;
      PROC PRINT DATA=__NUMCAR(DROP=TYPE N);
        ID VAR;
        TITLE4 "ERREUR : LES VARIABLES SUIVANTES SONT DÉCLARÉES COMME"
               " NUMÉRIQUES (N=0)";
        TITLE5 "DANS LA TABLE %UPCASE(&&&MAR)";
        TITLE6 "SPÉCIFIÉE DANS LE PARAMÈTRE &MAR,";
        TITLE7 "ALORS QUE CE SONT DES VARIABLES CARACTÈRES";
        TITLE8 "DANS LA TABLE %UPCASE(&&&DATA&NIV)";
        TITLE9 "SPÉCIFIÉE DANS LE PARAMÈTRE DATA&NIV";
       RUN;
    %END;
  %END;
 PROC DATASETS DDNAME=WORK NOLIST;
      DELETE __DATAM __DATAMA __COMP __NUMCAR;
 QUIT;
%MEND VERIF3;
